/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package oop.views;
import oop.model.Biodata;
/**
 *
 * @author hp
 */
public class PreviewDialog extends javax.swing.JFrame {
String nama, kls, jk, almat, jrsan;
    /**
     * Creates new form PreviewDialog
     */
    public PreviewDialog(String nama, String kls, String jk, String almat, String jrsan) {
        initComponents();
        
        Biodata bio = new Biodata(nama, kls, jk, almat, jrsan);
        nama = bio.getNama();
        kls = bio.getKls();
        jk = bio.getJk();
        almat = bio.getAlmt();
        jrsan = bio.getJrs();
        
        txtnama.setText(nama);
        txtkel.setText(kls);
        txtjk.setText(jk);
        txtal.setText(almat);
        txtjr.setText(jrsan);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tombolkeluar = new javax.swing.JButton();
        txtnama = new javax.swing.JLabel();
        txtkel = new javax.swing.JLabel();
        txtjk = new javax.swing.JLabel();
        txtal = new javax.swing.JLabel();
        txtjr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tombolkeluar.setText("Keluar");
        tombolkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolkeluarActionPerformed(evt);
            }
        });

        txtnama.setText("Nama : ");

        txtkel.setText("Kelas :");

        txtjk.setText("Jenis Kelamin :");

        txtal.setText("Alamat :");

        txtjr.setText("Jurusan :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtjr)
                    .addComponent(txtal)
                    .addComponent(txtnama)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtjk)
                        .addComponent(txtkel, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(254, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tombolkeluar)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txtnama)
                .addGap(18, 18, 18)
                .addComponent(txtkel)
                .addGap(18, 18, 18)
                .addComponent(txtjk)
                .addGap(18, 18, 18)
                .addComponent(txtal)
                .addGap(18, 18, 18)
                .addComponent(txtjr)
                .addGap(41, 41, 41)
                .addComponent(tombolkeluar)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolkeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_tombolkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreviewDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreviewDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreviewDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreviewDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreviewDialog("","","","","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton tombolkeluar;
    private javax.swing.JLabel txtal;
    private javax.swing.JLabel txtjk;
    private javax.swing.JLabel txtjr;
    private javax.swing.JLabel txtkel;
    private javax.swing.JLabel txtnama;
    // End of variables declaration//GEN-END:variables
}
